assessments/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('mines/', views.MineList.as_view(), name='mine_list'),
    path('mines/<pk>/', views.MineDetail.as_view(), name='mine_detail'),
    path('questions/', views.AnswerQuestions.as_view(), name='answer_questions'),
    path('assessment/<pk>/', views.AssessmentDetail.as_view(), name='assessment_detail')
]

django_msat/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import include, path
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('assessments.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

assessments/models.py
import uuid as uuid_lib

from django.db import models
from django.db.models import Count, Q
from django.contrib.auth.models import User
from django.urls import reverse

from django_msat.storage_backends import (PublicMediaStorage, 
    PrivateMediaStorage)

class Company(models.Model):

    name = models.CharField(max_length=255)

    class Meta(object):
        verbose_name_plural = 'Companies'

    def __str__(self):
        return self.name

class Country(models.Model):
    AMERICA = 'america'
    EUROPE = 'europe'
    AFRICA = 'africa'
    ASIA = 'asia'
    OCEANIA = 'oceania'
    REGION_CHOICES = (
        (AMERICA, 'Americas'),
        (EUROPE, 'Europe'),
        (AFRICA, 'Africa'),
        (ASIA, 'Asia'),
        (OCEANIA, 'Oceania')
    )

    name = models.CharField(max_length=255)
    region = models.CharField(max_length=100,
        choices=REGION_CHOICES, blank=True)
    code = models.CharField(max_length=2, blank=True)

    class Meta(object):
        ordering = ('name',)
        verbose_name_plural = 'Countries'

    def __str__(self):
        return self.name

class Mine(models.Model):

    name = models.CharField(max_length=255)
    company = models.ForeignKey(Company, 
        on_delete=models.SET_NULL, blank=True, null=True)
    country = models.ForeignKey(Country,
        on_delete=models.SET_NULL, blank=True, null=True)
    location = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('mine_detail', kwargs={'pk':self.id})

    def get_avg_score(self):
        responses = Response.objects.filter(
            assessment__mine=self).distinct()
        if responses:
            yeses = responses.filter(response=True)
            return (yeses.count() / responses.count()) * 100
        return None

class QuestionCategory(models.Model):

    order_id = models.IntegerField()
    name = models.CharField(max_length=255)
    about = models.TextField()

    class Meta(object):
        ordering = ('order_id',)
        verbose_name_plural = 'Question categories'

    def __str__(self):
        return self.name

class Question(models.Model):

    order_id = models.IntegerField()
    name = models.CharField(max_length=255)
    category = models.ForeignKey(QuestionCategory, 
        on_delete=models.CASCADE)

    class Meta(object):
        ordering = ('category', 'order_id',)

    def __str__(self):
        return self.name

class Assessment(models.Model):

    uuid = models.UUIDField(db_index=True, 
        default=uuid_lib.uuid4, editable=False)
    date = models.DateTimeField(auto_now_add=True)
    mine = models.ForeignKey(Mine, on_delete=models.CASCADE)
    user = models.ForeignKey(User, 
        on_delete=models.SET_NULL, blank=True, null=True)
    document = models.FileField(storage=PrivateMediaStorage(), 
        upload_to='private/', blank=True, null=True)

    def __str__(self):
        return '{} Assessment'.format(self.mine.name)

    def get_absolute_url(self):
        return reverse('assessment_detail', 
            kwargs={'pk':self.id})

    def get_score(self):
        responses = self.response_set.all()
        yeses = responses.filter(response=True)
        return (yeses.count() / responses.count()) * 100

    def get_responses_by_category(self):
        categories = {}
        yes = Count('response', filter=Q(response=True))
        no = Count('response', filter=Q(response=False))
        for category in QuestionCategory.objects.all():
            yes, no, null, count = 0,0,0,0
            responses = self.response_set.filter(
                question__category=category)
            for i in responses:
                count +=1
                if i.response == True:
                    yes += 1
                elif i.response == False:
                    no += 1
                else:
                    null +=1
            counts = (yes, no, null, count)
            categories[category.name] = (
                category.about, responses, counts)
        return categories

    def get_response_count_by_category(self):
        categories = {}
        yes = Count('response', filter=Q(response=True))
        no = Count('response', filter=Q(response=False))
        for category in QuestionCategory.objects.all():
            yes, no, null = 0,0,0
            responses = self.response_set.filter(
                question__category=category)
            for i in responses:
                if i.response == True:
                    yes += 1
                elif i.response == False:
                    no += 1
                else:
                    null +=1
            categories[category.name] = (yes, no, null) 
        return categories

class Response(models.Model):

    question = models.ForeignKey(Question, 
        on_delete=models.CASCADE)
    response = models.BooleanField(null=True)
    assessment = models.ForeignKey(Assessment, 
        on_delete=models.CASCADE)

    def __str__(self):
        return self.get_answer()

    def get_answer(self):
        if self.response == True:
            return 'Yes'
        elif self.response == False:
            return 'No'
        return 'N/A'

assessments/forms.py
from django import forms
from django.forms import inlineformset_factory

from assessments.models import (Company, Country, Mine, 
    QuestionCategory, Question, Assessment)



class AssessmentForm(forms.Form):

    pass
    

assessments/views.py
from django.conf import settings
from django.contrib import messages
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.generic import DetailView, ListView, View

from assessments.models import (Mine, Company,
    QuestionCategory, Question, Assessment, Response)

class Home(View):

    def get(self, request):
        return render(request, 'home.html')

class MineList(ListView):
    model = Mine

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['maps_api_key'] = settings.GOOGLEMAPS_API_KEY
        return context

class MineDetail(DetailView):
    model = Mine

class AssessmentList(ListView):
    model = Assessment

class AssessmentDetail(DetailView):
    model = Assessment

class AnswerQuestions(ListView):
    model = Question

    def post(self, request):
        company, mine, assessment = self.get_assessment(
            request)
        for key, value in request.POST.items():
            print(key, value)
            self.create_response(key, value, assessment)
        self.add_null_responses(assessment)
        messages.success(request, 
            'Assessment Received; Thank You!')
        return redirect(reverse('assessment_detail', 
            kwargs={'pk':assessment.id}))

    def get_assessment(self, request):
        company, created = Company.objects.get_or_create(
            name=request.POST.get('company')
        )
        mine, created = Mine.objects.get_or_create(
            name=request.POST.get('mine'),
            company=company,
            location=request.POST.get('location')
        )
        assessment = Assessment.objects.create(
            mine=mine,
        )
        if request.user.is_authenticated:
            assessment.user =request.user
            assessment.save()
        return company, mine, assessment

    def create_response(self, key, value, assessment):
        try:
            question = Question.objects.get(id=int(key))
            response = Response.objects.create(
               question=question,
               response=self.get_response(value),
               assessment=assessment
            )
        except Exception as error:
            print(error)

    def get_response(self, response):
        if response == 'True':
            return True
        else:
            return False

    def add_null_responses(self, assessment):
        remaining_questions = Question.objects.exclude(
            response__assessment=assessment).distinct()
        for question in remaining_questions:
            Response.objects.create(
                assessment=assessment,
                question=question,
            )

assessments/templates/assessments/assessment_detail.html
{% extends 'base.html' %}
{% block head %}
{% endblock %}
{% block content %}
  <div>
    <h3>Assessment: {{ assessment.mine.name }}</h3>
    <h4 class="">Company: {{ assessment.mine.company.name }}</h4>
    <h4>Location: {{ assessment.mine.location }}</h4>
    <h4>Date {{ assessment.date }}
  </div>
  <div class="mt-5 border-top">
    <h3 class="mt-4">Results</h3>
    <div id="id_categoryResults"></div>
    {% for category, data in assessment.get_responses_by_category.items %}
    <h4 class="mt-5">{{ category }} ({{ data.2.0 }}/{{ data.2.3 }})</h4>
    <p>{{ data.0 }}</p>
    <table class="table">
      <thead>
        <tr>
          <th>Question</th>
          <th class="text-center">Compliance</th>
        </tr>
      </thead>
      <tbody>
      {% for response in data.1 %}
        <tr>
          <td class="align-middle">{{ response.question.name }}</td>
          <td class="text-center">{% if response.response == False %}<i class="fas fa-times fa-2x text-danger"></i>{% elif response.response == True %}<i class="fas fa-check fa-2x text-success"></i>{% else %}<i class="fas fa-question fa-lg py-2"></i>{% endif %}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
    {% endfor %}
  </div>
{% endblock %}
{% block javascript %}
  <script type="text/javascript">
    google.charts.load("current", {packages:["corechart"]});
    google.charts.setOnLoadCallback(drawChart);
    function drawChart() {
      var data = google.visualization.arrayToDataTable([
        ["Category", "Yes", "No", "N/A", { role: "annotation" } ],
        {% for cat, values in assessment.get_responses_by_category.items %}
        ["{{ cat }}", {{ values.2.0 }}, {{ values.2.1 }}, {{ values.2.2 }}, ""],
        {% endfor %}
      ]);

      var options = {
        height: 800,
        bar: {groupWidth: "95%"},
        legend: { position: "top" },
        isStacked: 'percent',
      };
      var chart = new google.visualization.BarChart(document.getElementById("id_categoryResults"));
      chart.draw(data, options);
  }
  </script>
{% endblock %}

assessments/templates/assessments/mine_detail.html
{% extends 'base.html' %}
{% block head %}
<meta property="og:title" content="{{ mine.name }}" />
<meta property="og:url" content="https://www.rmf-msat.herokuapp.com{{ mine.get_absolute_url }}" />
<meta property="og:type" content="article" />
<meta property="og:description" content="{{ mine.name }}, {{ mine.company }}, {{ mine.location }}" />
{% endblock %}
{% block content %}
  <div>
    <h3>Mine site name: {{ mine.name }}</h3>
    <h4 class="">Company: {{ mine.company.name }}</h4>
    <h4>Location: {{ mine.location }}</h4>
  </div>
  <div class="border-top">
    <h3 class="pt-5">Assessments of this mine</h3>
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th scope="col">Date</th>
          <th scope="col">Conducted By</th>
          <th scope="col">Score</th>
        </tr>
      </thead>
      <tbody>
      {% for assessment in mine.assessment_set.all %}
        <th scope="row"><a href="{{ assessment.get_absolute_url }}">{{ assessment.date }}</a></th>
        <td><a href="{{ assessment.get_absolute_url }}">{{ assessment.user }}</a></td>
        <td><a href="{{ assessment.get_absolute_url }}">{{ assessment.get_score|stringformat:"d%%" }}</a></td>
      {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

assessments/templates/assessments/mine_list.html
{% extends 'base.html' %}
{% block head %}
{% endblock %}
{% block content %}
  <div class="container">
  <h3>Mines</h3>
    <div id="id_mineMap"></div>
    <div class="mt-5">
      <table class="table table-striped table-hover">
        <thead class="thead-light">
          <tr>
            <th scope="col">Site Name</th>
            <th scope="col">Company</th>
            <th scope="col">Location</th>
            <th scope="col"><div class="text-center">Assessments</div></th>
            <th scope="col"><div class="text-center">Avg Score</div></th>
          </tr>
        </thead>
        <tbody>
        {% for mine in mine_list %}
        <tr>
          <th scope="row">
            <a href="{% url 'mine_detail' pk=mine.id %}">{{ mine.name }}</a>
          </th>
          <td>
            <a href="{% url 'mine_detail' pk=mine.id %}">{{ mine.company.name }}</a>
          </td>
          <td>
            <a href="{% url 'mine_detail' pk=mine.id %}">{{ mine.country.name }}</a>
          </td>
          <td class="text-center">
            <a href="{% url 'mine_detail' pk=mine.id %}">{{ mine.assessment_set.count }}</a>
          </td>
          <td class="text-center">
            <a href="{% url 'mine_detail' pk=mine.id %}">{{ mine.get_avg_score|stringformat:"d%%" }}</a>
          </td>
        </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}
{% block javascript %}
  <script type='text/javascript'>
    google.charts.load('current', {
      'packages': ['geochart'],
      'mapsApiKey': '{{ maps_api_key }}'
    });
    google.charts.setOnLoadCallback(drawMarkersMap);

    function drawMarkersMap() {
    var data = google.visualization.arrayToDataTable([
      ['Location',   'Mines'],
      {% for mine in mine_list %}
      {% if mine.country %}
      ['{{ mine.country }}',1],
      {% endif %}
      {% endfor %}
    ]);

    var options = {
      displayMode: 'markers',
      legend: 'none',
    };

    var chart = new google.visualization.GeoChart(document.getElementById('id_mineMap'));
    chart.draw(data, options);
    };
  </script>
{% endblock %}

assessments/templates/assessments/question_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block head %}
<meta property="og:title" content="Mine Site Assessment Tool" />
<meta property="og:url" content="https://www.rmf-msat.herokuapp.com{{ mine.get_absolute_url }}" />
<meta property="og:type" content="article" />
<!-- <meta property="og:description" content="Assess " /> -->
{% endblock %}
{% block content %}
  <form method="POST">
    {% csrf_token %}
    <div class="container">
      <h3 class="h4">Complete an Assessment</h3>
    </div>
    <div class="container border p-2 mb-4">
      <div class="form-group row">
        <label class="col-2 col-form-label">Mine site name:</label>
        <div class="col-3 col-form-label">
            <input type="text" name="mine" class="select w-100">
        </div>
      </div>
      <div class="form-group row">
        <label class="col-2 col-form-label">Company name:</label>
        <div class="col-3 col-form-label">
          <input type="text" name="company" class="w-100"></div>
      </div>
      <div class="form-group row">
        <label class="col-2 col-form-label">Location:</label>
        <div class="col-3 col-form-label">
          <input type="text" name="location" class="w-100"></div>
      </div>
    </div>
    <div>
    {% regroup question_list by category as category_group %}
    {% for category in category_group %}
      <div class="container border mb-4">
        <div class="row border-bottom row-striped">
          <div class="col-8">
            <div class="row">
              <div class="col h4 pt-1">{{ category.grouper.order_id }}</div>
              <div class="col-11 font-weight-bold h4 pt-1">{{ category.grouper }}</div>
            </div>
          </div>
          <div class="col-4"></div>
        </div>
        <div class="New row border-bottom row-striped">
          <div class="col-6">
            <div class="row">
              <div class="col"></div>
              <div class="col-11">For this mine site, does the company:</div>
            </div>
          </div>
          <div class="col-4"></div>
          <div class="col-2">
            <div class="row">
              <div class="col text-center"><strong>No</strong></div>
              <div class="col text-center"><strong>Yes</strong></div>
            </div>
          </div>
        </div>
        {% for question in category.list %}
        <div class="row row-striped">
          <div class="col-8">
            <div class="row">
              <div class="col">{{ question.order_id }}</div>
              <div class="col-11">{{ question }}</div>
            </div>
          </div>
          <div class="col-2"></div>
          <div class="col-2">
            <div class="row">
              <div class="col text-center"><input type="radio" value="False" name="{{ question.id }}"></div>
              <div class="col text-center"><input type="radio" value="True" name="{{ question.id }}"></div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    {% endfor %}
    </div>
    <div class="container">
      <div class="row">
        <div class="col-10">
        </div>
        <div class="col-2">
          <input class="btn btn-primary btn-lg w-100" type="submit" value="Submit">
        </div>
      </div>
    </div>
  </form>
{% endblock %}